website/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'mysecret'

    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/auth/')

    return app

website/auth.py
from flask import Blueprint, render_template, redirect, url_for
from website import api
auth = Blueprint("auth", __name__)

@auth.route("/login")
def login():
    return render_template( 
        "login.html",
    )

website/views.py
from flask import Blueprint, render_template, redirect, url_for
from website import api

views = Blueprint("views", __name__)

@views.route("/pemancingan")
def list_pemancingan():

    # Query ke pemancingan
    return render_template( 
        "list_pemancingan.html",  
        active_page="pemancingan",
        informasi_pemancingan = api.list_pemancingan()
    )

@views.route("/")
def redirect_to_pemancingan():
    # Redirect to /pemancingan
    return redirect(url_for('views.list_pemancingan'))


@views.route("/pemancingan/<int:id>")
def detail_pemancingan(id):

    # Query ke pemancingan
    return render_template( 
        "detail_pemancingan.html",  
        active_page="pemancingan",
        informasi_pemancingan = api.detail_pemancingan(id)
    ) 

@views.route("/pemancingan/<int:id>/reservasi")
def reservasi_pemancingan(id):
    return render_template( 
        "reservasi.html",  
        active_page="pemancingan",
        informasi_pemancingan = api.detail_pemancingan(id)
    )

@views.route("/histori_reservasi")
def reservasi():
    return render_template( 
        "histori_reservasi.html",  
        active_page="reservasi"
    )                                       

@views.route("/profile")
def profile():
    return render_template( 
        "profile.html",  
        active_page="profile"
    )

website/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.6.0/css/fontawesome.min.css" integrity="sha384-NvKbDTEnL+A8F/AA5Tc5kmMLSJHUO868P+lDtTpJIeQdGYaUIuLr4lVGOEA1OcMy" crossorigin="anonymous">
        <link href='http://fonts.googleapis.com/css?family=Inter:400,300,700' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main-theme.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/navbar.css') }}">
        {% block page_specified_style %}{% endblock %}

        <title>{% block title %} Home {% endblock %}</title>
    </head>
    <body>
        <div class="content-wrapper">
            {% block content %}{% endblock %}
        </div>

        <nav class="navbar navbar-custom">
            <div class="container-fluid d-flex justify-content-center align-items-center" style="height: 100%;">
                <div class="row w-100">
                    <div class="col text-center">
                        <div class="d-grid">
                            <a class="btn text-decoration-none" href="{{ url_for('views.list_pemancingan') }}">
                                <div class="d-flex flex-column align-items-center">
                                    <div class="{% if active_page == 'pemancingan' %}icon-container{% endif %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="#FFFFFF" viewBox="0 0 256 256"><path d="M168,76a12,12,0,1,1-12-12A12,12,0,0,1,168,76Zm48.72,67.64c-19.37,34.9-55.44,53.76-107.24,56.1l-22,51.41A8,8,0,0,1,80.1,256l-.51,0a8,8,0,0,1-7.19-5.78L57.6,198.39,5.8,183.56a8,8,0,0,1-1-15.05l51.41-22c2.35-51.78,21.21-87.84,56.09-107.22,24.75-13.74,52.74-15.84,71.88-15.18,18.64.64,36,4.27,38.86,6a8,8,0,0,1,2.83,2.83c1.69,2.85,5.33,20.21,6,38.85C232.55,90.89,230.46,118.89,216.72,143.64Zm-55.18,29a52.11,52.11,0,0,1-33.4-44.78A52.09,52.09,0,0,1,83.37,94.47q-10.45,23.79-11.3,57.59a8,8,0,0,1-4.85,7.17L31.83,174.37l34.45,9.86a8,8,0,0,1,5.49,5.5l9.84,34.44,15.16-35.4a8,8,0,0,1,7.17-4.84Q137.71,183.12,161.54,172.64ZM212.42,43.57c-14.15-3-64.1-11-100.3,14.75a81.21,81.21,0,0,0-16,15.07,36,36,0,0,0,39.35,38.44,8,8,0,0,1,8.73,8.73,36,36,0,0,0,38.47,39.34,80.81,80.81,0,0,0,15-16C223.42,107.73,215.42,57.74,212.42,43.57Z"></path></svg>
                                    </div>
                                    <div class="navbar-text-custom text-center mt-1">
                                        Pemancingan
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col text-center">
                        <div class="d-grid">
                            <a class="btn text-decoration-none" href="{{ url_for('views.reservasi') }}">
                                <div class="d-flex flex-column align-items-center">
                                    <div class="{% if active_page == 'reservasi' %}icon-container{% endif %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="#FFFFFF" viewBox="0 0 256 256"><path d="M136,80v43.47l36.12,21.67a8,8,0,0,1-8.24,13.72l-40-24A8,8,0,0,1,120,128V80a8,8,0,0,1,16,0Zm-8-48A95.44,95.44,0,0,0,60.08,60.15C52.81,67.51,46.35,74.59,40,82V64a8,8,0,0,0-16,0v40a8,8,0,0,0,8,8H72a8,8,0,0,0,0-16H49c7.15-8.42,14.27-16.35,22.39-24.57a80,80,0,1,1,1.66,114.75,8,8,0,1,0-11,11.64A96,96,0,1,0,128,32Z"></path></svg>
                                    </div>
                                    <div class="navbar-text-custom text-center mt-1">
                                        Reservasi
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    <div class="col text-center">
                        <div class="d-grid">
                            <a class="btn text-decoration-none" href="{{ url_for('views.profile') }}">
                                <div class="d-flex flex-column align-items-center">
                                    <div class="{% if active_page == 'profile' %}icon-container{% endif %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="36" height="36" fill="#FFFFFF" viewBox="0 0 256 256"><path d="M230.92,212c-15.23-26.33-38.7-45.21-66.09-54.16a72,72,0,1,0-73.66,0C63.78,166.78,40.31,185.66,25.08,212a8,8,0,1,0,13.85,8c18.84-32.56,52.14-52,89.07-52s70.23,19.44,89.07,52a8,8,0,1,0,13.85-8ZM72,96a56,56,0,1,1,56,56A56.06,56.06,0,0,1,72,96Z"></path></svg>
                                    </div>
                                    <div class="navbar-text-custom text-center mt-1">
                                        Profile
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </nav>

        <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
        <script src="{{ url_for('static', filename='js/helper.js') }}"></script>
        
        {% block page_specified_script %}{% endblock %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js" integrity="sha512-2rNj2KJ+D8s1ceNasTIex6z4HWyOnEYLVC3FigGOmyQCZc2eBXKgOxQmo3oKLHyfcj53uz4QMsRCWNbLd32Q1g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.3/js/bootstrap.min.js" integrity="sha512-ykZ1QQr0Jy/4ZkvKuqWn4iF3lqPZyij9iRv6sGqLRdTPkY69YX6+7wvVGmsdBbiIfN/8OdsI7HABjvEok6ZopQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    </body>
</html>

website/templates/detail_pemancingan.html
{% extends "base.html" %} 

{% block title %}Beranda{% endblock %}

{% block page_specified_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/detail_pemancingan/card.css') }}">
{% endblock %}

{% block content %}

    <div class="d-flex justify-content-between align-items-center mt-1 mb-4">
        <div class="page-title"><b>Detail</b></div>
        <a href="{{ url_for('views.list_pemancingan') }}" class="btn theme-button-danger-custom ps-5 pe-5"><b>Kembali</b></a>
    </div>

    <img src="{{ url_for('static', filename='images/' ~ informasi_pemancingan['image_url']) }}" class="detail-pemancingan-img mt-1" alt="...">

    <div class="card h-100 shadow detail-pemancingan-card mt-4">
        <div class="card-body">
            
            <!-- Should not flex -->
            <div class="d-flex justify-content-between g-1 mb-2">
                <a href="{{informasi_pemancingan['link_map']}}" class="btn shadow theme-button-neutral-custom flex-grow-1 me-1"><b>Lihat Maps</b></a>
                <a href="{{ url_for('views.reservasi_pemancingan', id=informasi_pemancingan['id']) }}" class="btn shadow theme-button-neutral-alt-custom flex-grow-1 ms-1"><b>Buat Reservasi</b></a>
            </div> 

            <div class="row p-1">
                <div class="detail-pemancingan-card-title"><b>{{informasi_pemancingan['nama']}}</b></div>
                <div class="detail-pemancingan-card-text mb-3 mt-2 fw-lighter">{{informasi_pemancingan['description']}}</div>
    
                <div class="detail-pemancingan-card-text"><b>Lokasi</b></div>
                <div class="d-flex align-items-start">
                    <svg class="me-2 flex-shrink-0" width="28" height="28" xmlns="http://www.w3.org/2000/svg" fill="#FFFFFF" viewBox="0 0 256 256">
                        <path d="M128,64a40,40,0,1,0,40,40A40,40,0,0,0,128,64Zm0,64a24,24,0,1,1,24-24A24,24,0,0,1,128,128Zm0-112a88.1,88.1,0,0,0-88,88c0,31.4,14.51,64.68,42,96.25a254.19,254.19,0,0,0,41.45,38.3,8,8,0,0,0,9.18,0A254.19,254.19,0,0,0,174,200.25c27.45-31.57,42-64.85,42-96.25A88.1,88.1,0,0,0,128,16Zm0,206c-16.53-13-72-60.75-72-118a72,72,0,0,1,144,0C200,161.23,144.53,209,128,222Z"></path>
                    </svg>
                    <span class="detail-tag-text flex-grow-1 mt-1">
                        {{informasi_pemancingan['alamat']}}
                    </span>
                </div>

                {% if informasi_pemancingan['biaya_tempat'] is not none %}
                <div class="detail-pemancingan-card-text mt-1"><b>Biaya Tempat</b></div>
                <div class="d-flex align-items-start">
                    <svg class="me-2 flex-shrink-0" width="28" height="28" xmlns="http://www.w3.org/2000/svg" fill="#FFFFFF" viewBox="0 0 256 256">
                        <path d="M128,88a40,40,0,1,0,40,40A40,40,0,0,0,128,88Zm0,64a24,24,0,1,1,24-24A24,24,0,0,1,128,152ZM240,56H16a8,8,0,0,0-8,8V192a8,8,0,0,0,8,8H240a8,8,0,0,0,8-8V64A8,8,0,0,0,240,56ZM193.65,184H62.35A56.78,56.78,0,0,0,24,145.65v-35.3A56.78,56.78,0,0,0,62.35,72h131.3A56.78,56.78,0,0,0,232,110.35v35.3A56.78,56.78,0,0,0,193.65,184ZM232,93.37A40.81,40.81,0,0,1,210.63,72H232ZM45.37,72A40.81,40.81,0,0,1,24,93.37V72ZM24,162.63A40.81,40.81,0,0,1,45.37,184H24ZM210.63,184A40.81,40.81,0,0,1,232,162.63V184Z"></path>
                    </svg>
                    <span class="detail-tag-text flex-grow-1 mt-1 price-formatted">
                        {{informasi_pemancingan['biaya_tempat']}}
                    </span>
                </div>
                {% endif %}

                <div class="detail-pemancingan-card-text mt-1"><b>Biaya Ikan</b></div>
                <div class="d-flex align-items-start">
                    <svg class="me-2 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="#FFFFFF" viewBox="0 0 256 256">
                        <path d="M168,76a12,12,0,1,1-12-12A12,12,0,0,1,168,76Zm48.72,67.64c-19.37,34.9-55.44,53.76-107.24,56.1l-22,51.41A8,8,0,0,1,80.1,256l-.51,0a8,8,0,0,1-7.19-5.78L57.6,198.39,5.8,183.56a8,8,0,0,1-1-15.05l51.41-22c2.35-51.78,21.21-87.84,56.09-107.22,24.75-13.74,52.74-15.84,71.88-15.18,18.64.64,36,4.27,38.86,6a8,8,0,0,1,2.83,2.83c1.69,2.85,5.33,20.21,6,38.85C232.55,90.89,230.46,118.89,216.72,143.64Zm-55.18,29a52.11,52.11,0,0,1-33.4-44.78A52.09,52.09,0,0,1,83.37,94.47q-10.45,23.79-11.3,57.59a8,8,0,0,1-4.85,7.17L31.83,174.37l34.45,9.86a8,8,0,0,1,5.49,5.5l9.84,34.44,15.16-35.4a8,8,0,0,1,7.17-4.84Q137.71,183.12,161.54,172.64ZM212.42,43.57c-14.15-3-64.1-11-100.3,14.75a81.21,81.21,0,0,0-16,15.07,36,36,0,0,0,39.35,38.44,8,8,0,0,1,8.73,8.73,36,36,0,0,0,38.47,39.34,80.81,80.81,0,0,0,15-16C223.42,107.73,215.42,57.74,212.42,43.57Z"></path>
                    </svg>
                    <span class="detail-tag-text flex-grow-1 mt-1 price-formatted-kg">
                        {{informasi_pemancingan['biaya_ikan']}}
                    </span>
                </div>

                <div class="detail-pemancingan-card-text mt-1"><b>Biaya Pengolahan</b></div>
                <div class="d-flex align-items-start">
                    <svg class="me-2 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="#FFFFFF" viewBox="0 0 256 256">
                        <path d="M231.87,32.13a27.84,27.84,0,0,0-39.32,0L18.34,206.4a8,8,0,0,0,3.86,13.45A160.67,160.67,0,0,0,58.4,224c32.95,0,65.92-10.2,96.95-30.23,31.76-20.5,50.19-43.82,51-44.81a8,8,0,0,0-.64-10.59L185.32,118l46.55-46.56A27.85,27.85,0,0,0,231.87,32.13ZM189.1,144.44a220.41,220.41,0,0,1-42.86,36.16c-34.43,22.1-69.94,30.92-105.77,26.3L146,101.33Zm31.46-84.3L174,106.7,157.32,90l46.55-46.56a11.8,11.8,0,0,1,16.69,16.69Z"></path></svg>
                    <span class="detail-tag-text flex-grow-1 mt-1 price-formatted-kg">
                        {{informasi_pemancingan['biaya_olah']}}
                    </span>
                </div>

                {% if informasi_pemancingan['kolam'] and informasi_pemancingan['kolam']|length > 0 %}
                <div class="detail-pemancingan-card-text mt-1"><b>Kolam</b></div>
                <div class="d-flex align-items-start">
                    <svg class="me-2 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="#FFFFFF" viewBox="0 0 256 256">
                        <path d="M231.87,32.13a27.84,27.84,0,0,0-39.32,0L18.34,206.4a8,8,0,0,0,3.86,13.45A160.67,160.67,0,0,0,58.4,224c32.95,0,65.92-10.2,96.95-30.23,31.76-20.5,50.19-43.82,51-44.81a8,8,0,0,0-.64-10.59L185.32,118l46.55-46.56A27.85,27.85,0,0,0,231.87,32.13ZM189.1,144.44a220.41,220.41,0,0,1-42.86,36.16c-34.43,22.1-69.94,30.92-105.77,26.3L146,101.33Zm31.46-84.3L174,106.7,157.32,90l46.55-46.56a11.8,11.8,0,0,1,16.69,16.69Z"></path></svg>
                    <span class="detail-tag-text flex-grow-1 mt-1">
                        {% for kolam in informasi_pemancingan['kolam'] %}
                        - {{kolam.nama}} ( Kapasitas: {{kolam.kapasitas}} )<br>
                        {% endfor %}
                    </span>
                </div>
                {% endif %}
                
                {% if informasi_pemancingan['jenis_ikan'] and informasi_pemancingan['jenis_ikan']|length > 0 %}
                <div class="detail-pemancingan-card-text mt-1"><b>Ikan</b></div>
                <div class="d-flex align-items-start">
                    <svg class="me-2 flex-shrink-0" xmlns="http://www.w3.org/2000/svg" width="28" height="28" fill="#FFFFFF" viewBox="0 0 256 256">
                        <path d="M168,76a12,12,0,1,1-12-12A12,12,0,0,1,168,76Zm42,79.08c-15.08,20.84-37.53,34.88-66.7,41.74-20.08,4.72-43.54,6-70.12,3.93q2.4,17.82,6.72,37.54a8,8,0,0,1-6.1,9.52,7.81,7.81,0,0,1-1.72.19,8,8,0,0,1-7.81-6.29q-4.89-22.36-7.41-42.62-20.22-2.51-42.58-7.41a8,8,0,0,1,3.43-15.63q19.7,4.32,37.5,6.73c-2.09-26.56-.78-50,3.93-70.06C66,83.55,80.05,61.1,100.88,46,115,35.76,140.15,23.64,179.27,24c21.19.21,40.83,4.33,43.81,6.08a8,8,0,0,1,2.83,2.83c1.75,3,5.87,22.59,6.08,43.78C232.21,98.31,228.57,129.44,210,155.08Zm-23.76,2.8A112.07,112.07,0,0,1,98.12,69.74C75.64,94,66.7,132.47,71.36,184.6,123.51,189.28,162,180.35,186.25,157.88ZM212.44,43.56a175.75,175.75,0,0,0-39.22-3.51c-24.34.64-44.71,6.49-60.76,17.39a96,96,0,0,0,86.09,86.1c10.91-16,16.76-36.42,17.4-60.76A175.82,175.82,0,0,0,212.44,43.56Z"></path>
                    </svg>
                    <span class="detail-tag-text flex-grow-1 mt-1">
                        {% for jenis_ikan in informasi_pemancingan['jenis_ikan'] %}
                        - {{jenis_ikan.nama}} ( {{jenis_ikan.jumlah}} Ekor )<br>
                        {% endfor %}
                    </span>
                </div>
                {% endif %}


            </div>

        </div>
    </div>

    

{% endblock %}

website/templates/histori_reservasi.html
{% extends "base.html" %} {% block title %}Reservasi{% endblock %}
{% block content %}

<div class="mt-1 mb-4">
    <h1 class=""><b>Histori Reservasi</b></h1>
</div>
<div class="me-md-3 ms-md-3 mb-5">
    <div class="d-flex ">
        <input type="text" class="form-control me-3" id="cariHistoriReservasi" placeholder="Cari Histori Reservasi">
        <button type="button" class="btn theme-button-neutral-custom">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#FFFFFF" viewBox="0 0 256 256"><path d="M229.66,218.34l-50.07-50.06a88.11,88.11,0,1,0-11.31,11.31l50.06,50.07a8,8,0,0,0,11.32-11.32ZM40,112a72,72,0,1,1,72,72A72.08,72.08,0,0,1,40,112Z"></path></svg>
        </button>
    </div>
</div>

{% endblock %}

website/templates/profile.html
{% extends "base.html" %} {% block title %}Reservasi{% endblock %}

{% block page_specified_style %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/reservasi/card.css') }}">
{% endblock %}

{% block content %}

<div class="d-flex justify-content-center align-items-center centered-content-custom">
    <div class="card shadow reservasi-dibuat-card">
        <div class="card-body me-1 ms-1">
            <div class="row">
                <div class="reservasi-dibuat-card-title"><b>Reservasi Berhasil Dibuat</b></div>
                <div class="reservasi-dibuat-card-small-text mb-3 mt-2 fw-lighter">Reservasi kamu akan di cek oleh pemilik pemancingan. </div>

                <div class="reservasi-dibuat-card-text mb-1"><b>Kode Reservasi</b></div>
                <div class="d-flex align-items-start">

                    <svg class="me-2 flex-shrink-0" width="28" height="28" xmlns="http://www.w3.org/2000/svg" fill="#FFFFFF" viewBox="0 0 256 256"><path d="M72,104a8,8,0,0,1,8-8h96a8,8,0,0,1,0,16H80A8,8,0,0,1,72,104Zm8,40h96a8,8,0,0,0,0-16H80a8,8,0,0,0,0,16ZM232,56V208a8,8,0,0,1-11.58,7.15L192,200.94l-28.42,14.21a8,8,0,0,1-7.16,0L128,200.94,99.58,215.15a8,8,0,0,1-7.16,0L64,200.94,35.58,215.15A8,8,0,0,1,24,208V56A16,16,0,0,1,40,40H216A16,16,0,0,1,232,56Zm-16,0H40V195.06l20.42-10.22a8,8,0,0,1,7.16,0L96,199.06l28.42-14.22a8,8,0,0,1,7.16,0L160,199.06l28.42-14.22a8,8,0,0,1,7.16,0L216,195.06Z"></path></svg>
                    <span class="reservasi-dibuat-card-text flex-grow-1 mt-1">
                        TESt
                    </span>
                </div>

                <a href="{{ }}" class="btn mt-3 theme-button-neutral-custom"><b>Kembali Ke Menu</b></a>
            </div>
        </div>
    </div>
</div>


{% endblock %}